[package]
name = "rust_ray_tracing"
version = "0.1.0"
authors = ["Or Gany <gangana3@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
